# This file is for Render.com deployment only. For Northflank, use the Dockerfile and follow the dashboard setup instructions in the README.
services:
  - type: web
    name: embedding-service
    env: python
    plan: starter  # or upgrade to paid plan for better performance
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: EMBEDDING_MODEL
        value: all-MiniLM-L6-v2
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
    autoDeploy: true 